import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
Clean Mermaid — an Obsidian plugin (MIT).
This file is generated by esbuild. Do not edit directly; see src/ instead.
*/`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	platform: "browser",
	define: {
		"import.meta.url": "importMetaUrlShim",
	},
	inject: ["scripts/import-meta-shim.js"],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}